[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_PREBUILD_GENERATE_ONLY = "true"

# Tambahkan baris ini untuk memaksa Netlify melewati error form
[[plugins]]
  package = "@netlify/plugin-nextjs@4"